Repository emulsify-ds/compound, pull requests merged in 2022-12, with the labels that each got.

#63 Feat: JSdoc Eslint Plugin
  .eslintrc.yml
  README.md
  components/02-molecules/tabs/tabs.js
  package-lock.json
  package.json
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review

#40 feat: Accordion Component
  components/01-atoms/buttons/button.twig
  components/01-atoms/images/icons/_icon.twig
  components/01-atoms/lists/list.twig
  components/01-atoms/text/headings/_heading.twig
  components/02-molecules/accordion/_accordion-item.twig
  components/02-molecules/accordion/_accordion.scss
  components/02-molecules/accordion/accordion.js
  components/02-molecules/accordion/accordion.stories.js
  components/02-molecules/accordion/accordion.twig
  components/02-molecules/accordion/accordion.yml
  images/icons/chevron-down.svg
  system.emulsify.json
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#47 feat: Video component
  components/01-atoms/video/_video.scss
  components/01-atoms/video/video-full.yml
  components/01-atoms/video/video.twig
  components/01-atoms/video/video.yml
  components/01-atoms/video/videos.stories.js
  components/01-atoms/videos/_video-embed.twig
  components/01-atoms/videos/_video-html5.twig
  components/01-atoms/videos/_video.scss
  components/01-atoms/videos/video-embed.js
  components/01-atoms/videos/video-embed.yml
  components/01-atoms/videos/video-html5.yml
  components/01-atoms/videos/video.twig
  components/01-atoms/videos/videos.stories.js
  system.emulsify.json
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#45 Feat: Code Component
  components/01-atoms/text/text.stories.js
  components/01-atoms/text/text/07-code.twig
  components/01-atoms/text/text/_text.scss
  components/01-atoms/text/text/code.yml
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🎉 Ready to Merge

#70 fix(69): removing check for alt attr before printing it
  components/01-atoms/images/image/_image.twig
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review

#73 fix: name variable fixed for using double underscore
  components/01-atoms/images/icons/icons.md
  components/01-atoms/images/icons/icons.twig
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review, 🐛 Bug

#77 fix(74): fixing select color contrast
  components/01-atoms/forms/select/_select.scss
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review

#78 fix(75): fixing text field border contrast
  components/01-atoms/forms/textfields/_textfields.scss
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review

#79 fix(76): placeholder-text-contrast
  components/01-atoms/forms/textfields/_textfields.scss
Labels: 🎉 Passes Code Review, 🎉 Passes Functional Review
